export const GET_WEATHER_FETCH = "GET_WEATHER_FETCH"

export const GET_WEATHER_SUCCESS = "GET_WEATHER_SUCCESS"

export const GET_WEATHER_ERROR = "GET_WEATHER_ERROR"

export const LOADING_WEATHER_FETCH = "LOADING_WEATHER_FETCH"
